name: inmobiliaria
services:
  inmobiliaria-db:
    image: mariadb:11.3.2
    container_name: inmobiliaria-db
    restart: always
    environment:
      MYSQL_USER: $MARIADB_USER
      MYSQL_PASSWORD: $MARIADB_PASSWORD
      MYSQL_DATABASE: $MARIADB_DATABASE
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
    ports:
      - "3306:3306"
    healthcheck:
      test: [ CMD, healthcheck.sh, --connect, --innodb_initialized ]
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - network-inmobiliaria
  api-inmobiliaria:
    image: raulpra/api-inmobiliaria
    container_name: api-inmobiliaria
    ports:
      - "8082:8082"
    depends_on:
      inmobiliaria-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: $PROFILE
    networks:
      - network-inmobiliaria
networks:
  network-inmobiliaria:
    driver: bridge
