name: Integration tests with Newman

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: mvn package
      - run: docker build -t api-inmobiliaria .
      - run: docker compose up -d
      - run: sleep 10
      - run: npm install -g newman
      - run: newman run tests_api_inmobiliaria.postman_collection.json -e local.postman_environment.json